---
title: "Twitter API"
author: "Huiting Song"
output: html_document
---

## In R

For R API, I used twitter to scratch keywords like 'Natural Gas','crude oil,'gasoline' to scratch users' attitudes about these energy.

```{r message=FALSE, warning=FALSE, include=FALSE}
library(selectr)
library(rvest)
library(xml2)
library(rtweet) # for scraping tweets
library(wordcloud2) # for generating really cool looking wordclouds
library(tm) # for text minning
library(dplyr) # loads of fun stuff including piping
library(ROAuth)
library(jsonlite)
library(httpuv)
library(twitteR)
```

```{r}
consumer_key = "zV2ER7zM1HzFUshDEHpJ8UuVS"
consumer_secret = "5uHStDPwbFxEfLZojqPP9eDcWWXgfNCwdVPe8VG0xFvPldjhHJ"
access_token = "1558952162692108289-bQDaHCqBuJZnXXqeQWnz7Pk1bhdiWm"
access_token_secret = "kSJLq0tng5MfaFHoxbc7GpQ6D4SaplXzthDrW2SzhTSpD"
bearer_token = "AAAAAAAAAAAAAAAAAAAAAEGthAEAAAAArntLVGGx5Q8Irzy%2BRTc2HdgQ7Vw%3DOR64kNsk2o0eqNl9KKZQKs7i2yzUoHEObJHwsQWiwesFtlQKdp"
```
```{r}
library(twitteR)
requestURL='https://api.twitter.com/oauth/request_token'
accessURL='https://api.twitter.com/oauth/access_token'
authURL='https://api.twitter.com/oauth/authorize'

s_key  = 'natural gas OR gasoline OR crude oil'
n_tweets = 250 

twitteR:::setup_twitter_oauth(consumer_key, consumer_secret,access_token,access_token_secret)
Search1<-twitteR::searchTwitter(s_key,n=n_tweets, since="2022-05-01",lang="en")
```
```{r}
TweetsDF<- twListToDF(Search1)
TweetsDF
write.csv(TweetsDF,"/Users/apple/Desktop/anly-501-project-HuitingSong/codes/01-data-gathering/twitterR.csv")
```